name: HANINI
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_secure_storage: ^9.0.0
  dio: ^5.1.1
  flutter_svg: ^2.0.4
  string_validator: ^1.0.0
  flutter_screenutil: ^5.7.0
  lottie: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  url_launcher: ^6.1.10
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  external_app_launcher: ^4.0.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_messaging_platform_interface: ^4.3.0
  change_app_package_name: ^1.1.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_logo.png"
  min_sdk_android: 21

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/animations/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: bahij
      fonts:
        - asset: assets/fonts/bahij_regular.ttf


